[package]
name = "barreras"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "banquero"
path = "src/banquero_barreras.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"